data:
  mapRoles: |
    - rolearn: arn:aws:iam::424976457053:role/EKSNodeRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::424976457053:user/capstone
      username: github
      groups:
        - system:masters